version: '3.7' 
services: 
  web: 
    build: project
    ports: 
      - '8000:8000'
    volumes:
      # app config files 
      - ./etc:/etc/openvpn-creds-ui
      # app logs
      - ./var:/var/log/openvpn-creds-ui
      # PKI
      - ./pki:/easy-rsa/pki
      # source code (also .env and db.sqlite3)
      - "./project:/usr/src/project"
